[versions]
min-sdk = "31"
compile-sdk = "36"
target-sdk = "36"
jdk = "21"
agp = "8.13.1"
kotlin = "2.2.21"
google-material = "1.13.0"
androidx-activity = "1.12.0"
androidx-compose-ui = "1.9.5"
androidx-compose-material3 = "1.4.0"
androidx-core-splashscreen = "1.2.0"

[libraries]
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }